# Generated by Django 3.0.1 on 2019-12-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('position', models.SmallIntegerField()),
                ('color', models.CharField(blank=True, default='#FFFFFF', max_length=7)),
            ],
            options={
                'ordering': ['position', 'created'],
            },
        ),
    ]
